TarinPood/Areas/Admin/Controllers/SliderController.cs
using Application.Services.Slider;
using Common.Alert;
using Microsoft.AspNetCore.Mvc;

namespace TarinPood.Areas.Admin.Controllers
{
    public class SliderController : AdminBaseController
    {
        private ISliderServices _sliderServices;
        public SliderController(ISliderServices sliderServices)
        {
            _sliderServices = sliderServices;
        }
        public IActionResult Index()
        {
            var res = _sliderServices.GetAllSliderForAdmin();

            return View(res.Data);
        }

        public IActionResult Add(string h2,string h5,int order,IFormFile image)
        {
            var res = _sliderServices.AddImageSlider(new AddImageSliderDto { SliderH2Content = h2, SliderH5Content = h5, SliderOrder = order }, image);

            if(res.IsSuccess)
            {
                notify("عملیات موفق", notifyType.success, res.Message);
            }
            else
            {
                notify("هشدار", notifyType.warning, res.Message);

            }

            return Redirect("/Admin/Slider");
        }

        public IActionResult Remove(int SliderId)
        {
            var res = _sliderServices.Remove(SliderId);

            return Json(res);
        }

        public IActionResult Edit(int SliderId, string SliderH2Content, string SliderH5Content, int SliderOrder)
        {
            var res = _sliderServices.Edit(SliderId, SliderH2Content, SliderH5Content, SliderOrder);
            return Json(res);
        }
    }
}

TarinPood/Areas/Admin/Controllers/UserController.cs
using Application.Services.User;
using Microsoft.AspNetCore.Mvc;

namespace TarinPood.Areas.Admin.Controllers
{
    public class UserController : AdminBaseController
    {
        private IUserServices _userServices;
        public UserController(IUserServices userServices)
        {
            _userServices = userServices;
        }
        public IActionResult Index()
        {
            var res = _userServices.GetAllUser();
            return View(res.Data);
        }

        public IActionResult Add(string name, string Password)
        {
            var res = _userServices.Add(name, Password);
            return Redirect("/Admin/User");
        }

        public IActionResult Edit(int UId,string UName, string UPassword)
        {
            var res = _userServices.EditUser(UId, UName.Trim().ToLower(), UPassword);
            return Json(res);
        }

        public IActionResult Remove(int UId)
        {
            var res = _userServices.Remove(UId);

            return Json(res);
        }
    }
}

TarinPood/Controllers/ProductController.cs
using Application.Services.Product.Querise.IGetProductForIndexService;
using Microsoft.AspNetCore.Mvc;

namespace TarinPood.Controllers
{
    public class ProductController : Controller
    {
        private IGetProductForIndexService _getProductForIndex;
        public ProductController(IGetProductForIndexService getProductForIndex)
        {
            _getProductForIndex = getProductForIndex;
        }
        public IActionResult Index()
        {
            var res = _getProductForIndex.Execute();
            return View(res.Data);
        }

        public IActionResult Detail(int id)
        {
            var res=_getProductForIndex.GetDetailProduct(id);

            if (res.IsSuccess != true)
            {
                return Redirect("/");
            }

            return View(res.Data);
        }
    }
}

TarinPood/Areas/Admin/Views/Shared/_Alert.cshtml
<script>
    @if (TempData["notify"] != null)
        @Html.Raw(TempData["notify"].ToString())
    </script>

TarinPood/Areas/Admin/Views/Shared/_FooterPartial.cshtml
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 footer-copyright text-center">
            <p class="mb-0">کپی رایت 2022 © تمامی حقوق محفوظ است </p>
        </div>
    </div>
</div>

TarinPood/Areas/Admin/Views/Shared/_HeaderPartial.cshtml
<div class="header-wrapper row m-0">
    <div class="header-logo-wrapper col-auto p-0">
        <div class="logo-wrapper">
            <a href="/">
                <img class="img-fluid" src=""
                     alt="">
            </a>
        </div>
        <div class="toggle-sidebar">
            <div class="status_toggle sidebar-toggle d-flex">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <g>
                        <g>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M21.0003 6.6738C21.0003 8.7024 19.3551 10.3476 17.3265 10.3476C15.2979 10.3476 13.6536 8.7024 13.6536 6.6738C13.6536 4.6452 15.2979 3 17.3265 3C19.3551 3 21.0003 4.6452 21.0003 6.6738Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M10.3467 6.6738C10.3467 8.7024 8.7024 10.3476 6.6729 10.3476C4.6452 10.3476 3 8.7024 3 6.6738C3 4.6452 4.6452 3 6.6729 3C8.7024 3 10.3467 4.6452 10.3467 6.6738Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M21.0003 17.2619C21.0003 19.2905 19.3551 20.9348 17.3265 20.9348C15.2979 20.9348 13.6536 19.2905 13.6536 17.2619C13.6536 15.2333 15.2979 13.5881 17.3265 13.5881C19.3551 13.5881 21.0003 15.2333 21.0003 17.2619Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd"
                                  d="M10.3467 17.2619C10.3467 19.2905 8.7024 20.9348 6.6729 20.9348C4.6452 20.9348 3 19.2905 3 17.2619C3 15.2333 4.6452 13.5881 6.6729 13.5881C8.7024 13.5881 10.3467 15.2333 10.3467 17.2619Z"
                                  stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                        </g>
                    </g>
                </svg>
            </div>
        </div>
    </div>
    <div class="left-side-header col ps-0 d-none d-md-block">
    </div>
    <div class="nav-right col-10 col-sm-6 pull-right right-header p-0">
        <ul class="nav-menus">
            <li>
                <div class="mode animated backOutRight">
                    <svg class="lighticon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <g>
                            <g>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M18.1377 13.7902C19.2217 14.8742 16.3477 21.0542 10.6517 21.0542C6.39771 21.0542 2.94971 17.6062 2.94971 13.3532C2.94971 8.05317 8.17871 4.66317 9.67771 6.16217C10.5407 7.02517 9.56871 11.0862 11.1167 12.6352C12.6647 14.1842 17.0537 12.7062 18.1377 13.7902Z"
                                      stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                            </g>
                        </g>
                    </svg>
                    <svg class="darkicon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <path d="M17 12C17 14.7614 14.7614 17 12 17C9.23858 17 7 14.7614 7 12C7 9.23858 9.23858 7 12 7C14.7614 7 17 9.23858 17 12Z">
                        </path>
                        <path d="M18.3117 5.68834L18.4286 5.57143M5.57144 18.4286L5.68832 18.3117M12 3.07394V3M12 21V20.9261M3.07394 12H3M21 12H20.9261M5.68831 5.68834L5.5714 5.57143M18.4286 18.4286L18.3117 18.3117"
                              stroke-linecap="round" stroke-linejoin="round"></path>
                    </svg>
                </div>
            </li>
            
    
        </ul>
    </div>
    <script class="result-template" type="text/x-handlebars-template">
        <div class="ProfileCard u-cf">
          <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
          <div class="ProfileCard-details">
          <div class="ProfileCard-realName">{{name}}</div>
          </div>
          </div>
    </script>
    <script class="empty-template" type="text/x-handlebars-template">
        <div class="EmptyMessage">جستجوی شما 0 نتیجه یافت. این به احتمال زیاد به این معنی است که بک اند پایین است!</div>
    </script>
</div>

TarinPood/Areas/Admin/Views/Shared/_SliderPartial.cshtml
<div>
    <div class="logo-wrapper">
        <a href="/">
            <img style="height:50px;border-radius:5px;" class="img-fluid for-light"
                 src="~/assets/images/tarinpood-logo.jpg" alt=""><img class="img-fluid for-dark"
                                                            src="~/assets/images/tarinpood-logo.jpg" alt="">
        </a>
        <div class="back-btn"><i class="fa fa-angle-right"></i></div>
    </div>
    <div class="logo-icon-wrapper">
        <a href="/">
            <img style="height :50px;border-radius:5px;" class="img-fluid"
                 src="~/assets/images/tarinpood-logo.jpg" alt="">
        </a>
    </div>
    <nav class="sidebar-main">
        <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
        <div id="sidebar-menu">
            <ul class="sidebar-links" id="simple-bar">
                <li class="back-btn">
                    <a href="/">
                        <img class="img-fluid" src=""
                             alt="">
                    </a>
                    <div class="mobile-back text-end">
                        <span>بازگشت</span><i class="fa fa-angle-left ps-2"
                                              aria-hidden="true"> </i>
                    </div>
                </li>

                <li class="sidebar-list">
                    <a class="sidebar-link sidebar-title link-nav" asp-area="admin" asp-controller="Home" asp-action="Index">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <g>
                                    <path d="M9.07861 16.1355H14.8936" stroke="#130F26" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round"></path>
                                    <path fill-rule="evenodd" clip-rule="evenodd"
                                          d="M2.3999 13.713C2.3999 8.082 3.0139 8.475 6.3189 5.41C7.7649 4.246 10.0149 2 11.9579 2C13.8999 2 16.1949 4.235 17.6539 5.41C20.9589 8.475 21.5719 8.082 21.5719 13.713C21.5719 22 19.6129 22 11.9859 22C4.3589 22 2.3999 22 2.3999 13.713Z"
                                          stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                            </g>
                        </svg><span >صفحه اصلی</span>
                        <div class="according-menu"><i class="fa fa-angle-left"></i></div>
                    </a>
                </li>
                <li class="sidebar-list">
                    <a class="sidebar-link sidebar-title" href="#">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <g>
                                    <path d="M15.7499 9.47167V6.43967C15.7549 4.35167 14.0659 2.65467 11.9779 2.64967C9.88887 2.64567 8.19287 4.33467 8.18787 6.42267V9.47167" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M2.94995 14.2074C2.94995 8.91344 5.20495 7.14844 11.969 7.14844C18.733 7.14844 20.988 8.91344 20.988 14.2074C20.988 19.5004 18.733 21.2654 11.969 21.2654C5.20495 21.2654 2.94995 19.5004 2.94995 14.2074Z" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                            </g>
                        </svg><span>محصولات</span>
                        <div class="according-menu"><i class="fa fa-angle-left"></i></div>
                    </a>
                    <ul class="sidebar-submenu" style="display: none;">
                        <li><a asp-area="Admin" asp-controller="Product" asp-action="AddNewProduct" asp-route-id="0">افزودن محصول جدید</a></li>
                        <li><a asp-area="Admin" asp-controller="Product" asp-action="Index" >لیست محصولات</a></li>
                        <li><a asp-area="Admin" asp-controller="Product" asp-action="Attributes">ویژگی های محصول</a></li>

                    </ul>
                </li>
                <li class="sidebar-list">
                    <a asp-area="Admin" asp-controller="Slider" asp-action="index" class="sidebar-link sidebar-title link-nav">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-server"><rect x="2" y="2" width="20" height="8" rx="2" ry="2"></rect><rect x="2" y="14" width="20" height="8" rx="2" ry="2"></rect><line x1="6" y1="6" x2="6" y2="6"></line><line x1="6" y1="18" x2="6" y2="18"></line></svg>                        <span>تصاویر اسلایدر</span>
                    </a>
                </li>
                <li class="sidebar-list">
                    <a asp-area="Admin" asp-controller="User" asp-action="index" class="sidebar-link sidebar-title link-nav">
                        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g>
                                <g>
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M9.55851 21.4562C5.88651 21.4562 2.74951 20.9012 2.74951 18.6772C2.74951 16.4532 5.86651 14.4492 9.55851 14.4492C13.2305 14.4492 16.3665 16.4342 16.3665 18.6572C16.3665 20.8802 13.2505 21.4562 9.55851 21.4562Z" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M9.55849 11.2776C11.9685 11.2776 13.9225 9.32356 13.9225 6.91356C13.9225 4.50356 11.9685 2.54956 9.55849 2.54956C7.14849 2.54956 5.19449 4.50356 5.19449 6.91356C5.18549 9.31556 7.12649 11.2696 9.52749 11.2776H9.55849Z" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M16.8013 10.0789C18.2043 9.70388 19.2383 8.42488 19.2383 6.90288C19.2393 5.31488 18.1123 3.98888 16.6143 3.68188" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                    <path d="M17.4608 13.6536C19.4488 13.6536 21.1468 15.0016 21.1468 16.2046C21.1468 16.9136 20.5618 17.6416 19.6718 17.8506" stroke="#130F26" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
                                </g>
                            </g>
                        </svg>
                        <span>مدیران سایت</span>
                    </a>
                </li>
                <li class="sidebar-list">
                    <a href="/Authentication/SignOut" class="sidebar-link sidebar-title link-nav">
                        <i data-feather="log-out"></i>
                        <span>خروج از حساب کاربری</span>
                    </a>
                </li>

            </ul>
        </div>
        <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
    </nav>
</div>